name: Lint and Test

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
        NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          cache: true
          cache-dependency-path: src/TodoApp.Api/packages.lock.json

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build and Linting
        run: dotnet build --no-restore --warnaserror

      - name: Testing
        run: dotnet test --no-build